### ISSUE TITLE
Track stalled cycles and/or branch misses

### ISSUE THREAD

**Issue by nagisa** [rust-lang/rustc-perf#1014]
Increasing stalled cycles can most readily indicate two distinct problems that do not get reflected as readily in the `instructions:u` or `cycles:u` measurements:

1. We're waiting on memory accesses for data that is not yet in the cache;
2. We miss a branch prediction and are waiting on a pipeline flush a lot (AFAIK?).

Both of these problems could help explaining mystery increases in wall time despite decreases in instruction counts.

**Comment by bjorn3** [comment]
The more PMU counters we record the less accurate the results will be. Cpu's only allow tracking a limited amount of PMU counters. If you try to track more, perf will continuously cycle through them, which reduces accurary.

**Comment by nagisa** [comment]
Do we know how many PMU counters can the Ryzen in our profiling box accurately measure at once?

**Comment by tgnottingham** [comment]
We panic if `perf stat` indicates that an event wasn't being measured 100% of the time. So we should be able to add this without fear of it reducing accuracy without us knowing about it.

Since some user's machines may not have as many counters as the profiling machine, we may want to do something like allow the user to configure which stats are collected. Otherwise, they could hit the panic.

**Comment by Kobzol** [comment]
Branch misses and cache misses were added in https://github.com/rust-lang/rustc-perf/pull/1392.

**Comment by nagisa** [comment]
Nice!
