### ISSUE TITLE
Request fails

### ISSUE THREAD

**Issue by younes-io** [rust-lang/rustc-perf#1083]
This request `https://perf.rust-lang.org/?start=2021-01-01&end=2021-10-17&kind=percentfromfirst&stat=wall-time` resumes with a `504` error

The frontend still shows even though the HTTP request failed:
`Loading & rendering data...
This may take a while!`

Expected behavior:
* The frontend should reflect the state of the request
* The request should not fail

**Comment by Mark-Simulacrum** [comment]
This is likely due to a timeout (I'm seeing the request take ~60-70 seconds locally). Likely this query is just too large in practice to run; we'd need to optimize the database search for it to be faster and that may not be entirely possible -- it's reading a *lot* of rows in. Regardless, we should do better about telling the user the request has failed.
