### ISSUE TITLE
Missing start commit for 90891

### ISSUE THREAD

**Issue by bjorn3** [rust-lang/rustc-perf#1163]
https://github.com/rust-lang/rust/pull/90891#issuecomment-1025606783

**Comment by Mark-Simulacrum** [comment]
It's in the queue - https://perf.rust-lang.org/status.html - I'm not sure why we benchmarked in the wrong order yet. My suspicion is that the PR result was incorrectly queued as a try build, which would prioritize it over master commits, though it would typically have the parent commit still precede it.

**Comment by bjorn3** [comment]
Should I close this issue then?

**Comment by klensy** [comment]
```
1/30/2022, 11:57:34 PM | 08df8b81d6e72 | #92711 - in progress
1/31/2022, 7:23:21 AM | bb549e5afe8f2 | #93270
1/31/2022, 11:12:10 AM | 415c9f95884ca | #93499
```
No, it's not in queue?

**Comment by Mark-Simulacrum** [comment]
The parent commit (rust-lang/rust@08df8b81d6e723c66fee579d57d61dc60bc21fc1) of #90891's merge (rust-lang/rust@e58e7b10e13595b4df1b105bfb9ad03c8dee7832) is in the queue -- currently in progress.

**Comment by klensy** [comment]
I thought, that if no parent for perf run exist, no benchmarks will be run at all, but i was wrong. It will run, but simply don't do comparison.
Perf run results for #90891 exist, so yes, upcoming runs should work :-)

**Comment by Mark-Simulacrum** [comment]
OK, I think I likely know what happened:

* rust-lang/rust@237000707ffe2 was queued as a try build
* This bumped priority for rust-lang/rust@e58e7b1 to run, since it was necessary for the try build
* Once rust-lang/rust@e58e7b1 ran, its results attempted to be posted, but the parent of that commit had not yet been benchmarked

I think it should be a relatively straightforward thing to change the queue code to fix this -- might actually represent a simplification since I think it'll probably mean dropping the prioritization logic.
