### ISSUE TITLE
Improved GitHub message after perf suite run

### ISSUE THREAD

**Issue by rylev** [rust-lang/rustc-perf#1214]
The following is an attempt to further improve the information we display after a perf suite run is performed. 

The proposed message below gives an extremely short summary followed by a table with the most relevant stats.

Thoughts?

## Proposal

Finished benchmarking commit (2c6a29af35a81e20f8af4c32bf1b55c59b89eccd): [comparison url](https://perf.rust-lang.org/compare.html?start=335ffbfa547df94ac236f5c56130cecf99c8d82b&end=2c6a29af35a81e20f8af4c32bf1b55c59b89eccd).

**Summary**:  😿relevant regressions found

|      | Regressions 😿 <br> (primary) | Regressions 😿<br>  (secondary) | Improvements 🎉 <br>  (primary) | Improvements 🎉<br>  (secondary) | 
|:---:|:-------------:|:-----------------:|:-------------:|:-----------------:|
| # <sup>1</sup>|  10 | 20| 0 | 7 |
| x̄ <sup>2</sup>| 0.9%| 10.0%| N/A | 4.0%|
| max | 1.6%<br> `incr-unchanged` of `syn check` | 3.4% <br> `incr-unchanged` of `deep-vector check` | N/A  | 3.4% <br> `incr-unchanged` of `externs doc`|

**Next Steps**: 
* **Justify**: If you can justify the regressions found in this perf run, please indicate this with `@rustbot label: +perf-regression-triaged` along with sufficient written justification. 
* **Open issue**: If you cannot justify the regressions please open an issue or create a new PR that fixes the regressions, add a comment linking to the newly created issue or PR, and then add the `perf-regression-triaged` label to this PR.

@rustbot label: +perf-regression

*Note: If you find an issue with this performance assessment, please file an issue in [rust-lang/rustc-perf](https://github.com/rust-lang/rustc-perf/issues/new).*

<sup>1</sup> *number of relevant changes*
<sup>2</sup> *the arithmetic mean of the percent change*

**Comment by Mark-Simulacrum** [comment]
I am not a fan of the "#" and x bar -- at least the latter doesn't render as well as I'd like for us to use it.

Maybe we can just write "count" and "mean", with footnotes or links clarifying?

I would also recommend dropping benchmark profile and name from the max row of the table -- I'm not sure they are particularly useful. I know I typically just ignore them, since a single point is unlikely to give that much meaning. That'll help tighten up the table and make it less arbitrarily wide, too.

---

Revised copy:


Finished benchmarking commit (2c6a29af35a81e20f8af4c32bf1b55c59b89eccd): [comparison url](https://perf.rust-lang.org/compare.html?start=335ffbfa547df94ac236f5c56130cecf99c8d82b&end=2c6a29af35a81e20f8af4c32bf1b55c59b89eccd).

**Summary**:  😿relevant regressions found

|      | Regressions 😿 <br> (primary) | Regressions 😿<br>  (secondary) | Improvements 🎉 <br>  (primary) | Improvements 🎉<br>  (secondary) | 
|:---:|-------------:|-----------------:|-------------:|-----------------:|
| count[^1] |  10 | 20| 0 | 7 |
| mean[^2] | 0.9%| 10.0%| N/A | 4.0%|
| max | 1.6% | 3.4% | N/A  | 3.4% |

**Next Steps**: 
* **Justify**: If you can justify the regressions found in this perf run, please indicate this with `@rustbot label: +perf-regression-triaged` along with sufficient written justification. 
* **Open issue**: If you cannot justify the regressions please open an issue or create a new PR that fixes the regressions, add a comment linking to the newly created issue or PR, and then add the `perf-regression-triaged` label to this PR.

rustbot label: +perf-regression

*Note: If you find an issue with this performance assessment, please file an issue in [rust-lang/rustc-perf](https://github.com/rust-lang/rustc-perf/issues/new).*

[^1]: *number of relevant changes*
[^2]: *the arithmetic mean of the percent change*

----

I might also transpose the table (i.e., columns switched with rows), since it seems like that might help scanning it more quickly for comparing a single stat across the table.

**Comment by rylev** [comment]
@Kobzol I think the version that @Mark-Simulacrum posted above is a definite improvement over what we have now. We can keep improving this in the future, but I don't see a reason to delay getting this change in now. Would you like to implement or shall I?

**Comment by Kobzol** [comment]
I'll implement it :) Since it's probably a bit difficult to test and this will be a big change, I'll try to debug print the output and paste it into GH on some tmp PR/issue to see how it looks like.
