### ISSUE TITLE
Dashboard page is out-of-date again

### ISSUE THREAD

**Issue by kamulos** [rust-lang/rustc-perf#1419]
See #771 

The newest release 1.63.0 and the newest beta is not available in the https://perf.rust-lang.org/dashboard.html page

**Comment by Mark-Simulacrum** [comment]
OK -- I would like to see an automated fix for this. I think @Kobzol you recently adjusted our next_commit code to take a proper commit, maybe you'd be interested in taking on adjusting that to take an ArtifactId or so? That way the backend can just use the normal queue rather than ad-hoc manual queueing.

Once that's done I think the best bet is to do something similar to the way we discover master commits, but use https://static.rust-lang.org/manifests.txt instead, putting the last beta and last stable release into the queue unless they've already been benchmarked (I don't think we need to backfill so that would be enough).
