### ISSUE TITLE
GH perf bot missing perf builds message completely for rollup

### ISSUE THREAD

**Issue by klensy** [rust-lang/rustc-perf#1424]
https://github.com/rust-lang/rust/pull/100977 is rollup of 8, but no perf builds message, like in https://github.com/rust-lang/rust/pull/100963#issuecomment-1226538733.

Probably because of rustc_codegen_cranelift sync with lots things in it.

Similar to #1390

**Comment by rylev** [comment]
👀 The webhook was successful which means the error happened when we're processing it in the background. I'll need to jump into the logs to find out more.

**Comment by rylev** [comment]
Looking at things more closely, it turns out that the mechanism mistakenly found 2 rollup merge commits because one of the rollup PRs itself contained rollup merge commits. Unfortunately, I'm pretty sure there's no way for us to detect that due to the issue found in https://github.com/rust-lang/rustc-perf/issues/1390.
