### ISSUE TITLE
Dashboard is more than a month out of date?

### ISSUE THREAD

**Issue by rvolgers** [rust-lang/rustc-perf#1704]
This is regarding https://perf.rust-lang.org/dashboard.html

The last data point is a beta from 2023-06-26, and it is missing the 1.71 release which happened a month ago.

I'm just a random person who noticed and decided to ask about it; so absolutely no pressure if this is bc something is broken.

Even if everything is working-as-intended it might be useful to mention the logic behind the timing of data points on the page itself or the help screen or something.

**Comment by Kobzol** [comment]
Oops, that's definitely not intended, I'll try to investigate. Thanks!

Also, good point with the help, I'll add it somewhere to explain how/when does the dashboard gather data.

**Comment by Kobzol** [comment]
We didn't have time to look into this yet. CC @Mark-Simulacrum

**Comment by Mark-Simulacrum** [comment]
This was due to manifests.txt not being updated by https://github.com/rust-lang/generate-manifest-list/actions, which times out after some number of days and requires a manual kick. I think the right fix is probably to move that processing over to a non-GHA job so that we don't deal with the cron limits, but it's somewhat low priority.

**Comment by Kobzol** [comment]
Created https://github.com/rust-lang/infra-team/issues/78 to track this. Closing this issue, as the dashboard is up to date for now.
I added an explanation of the dashboard data in https://github.com/rust-lang/rustc-perf/pull/1714.
