### ISSUE TITLE
Compile Time summary doesn't update when filters are changed even though the table does.

### ISSUE THREAD

**Issue by Zentrik** [rust-lang/rustc-perf#1850]
![image](https://github.com/rust-lang/rustc-perf/assets/19725290/c7bb1467-3457-465f-b830-646ce71f6922)
Note that the %s under Compile Time differ from the table. I assume this is unintended, sorry if not.

Here's the link to the [benchmark](https://perf.rust-lang.org/compare.html?primary=false&start=084ce5bdb5f7dc1c725f6770a8de281165ba3b0a&end=3cbb93223f33024db464a4df27a13c7cce870173&stat=instructions%3Au).

**Comment by Kobzol** [comment]
Hi, this is actually intended :sweat_smile:, in the sense that the code is not updating the top table at all. It should display the summary over all the data, and isn't affected by the filters.

I suppose that we could change it, but since the filters are below the tabs, and they do not affect the other tabs that are not activ (runtime benchmarks), I think that it's fine to keep it as it is.
