### ISSUE TITLE
Store data in a database instead of cloning git repo

### ISSUE THREAD

**Issue by ishitatsuyuki** [rust-lang/rustc-perf#228]
First, using PostgreSQL is the only way to persist state inside Heroku. We have seen some instances having a stale state in the past, so we should instead rely on a source that is centrally managed.

Second, using databases allows us to start up faster (no initial scan).

At last, data are stored in binary in databases, which is more efficient than JSON.

For fetching data, we would directly call the GitHub API to fetch added files. For the initial fetch, a tarball download can be used.

**Comment by Mark-Simulacrum** [comment]
In the past, I've been hesitant to use a database due to higher overhead for developers; while currently most can simply clone and run, a database will require greater setup. If there's some easy way for us to avoid that, then this seems fine.

I think the 2nd and 3rd concerns are non-issues at this point (at least in my experience) -- startup is effectively instant (sub-second, I believe) on a warm cache. Storage efficiency also seems like it shouldn't really matter.

I agree that a DB might help solve the stale state problem, but I'm hopeful that we can also resolve it without the overheads that introducing a DB will create. I plan to look into the problem more in the future; and I personally don't see it as too big an issue.

**Comment by nnethercote** [comment]
Please keep in mind that rustc-perf is also used for local timing runs. A local directory is used rather than a clone of the rustc-timings repo.

I use this functionality to evaluate every optimization I implement in rustc. From my point of view, JSON is great because it is extremely simple and I can use a text editor to inspect the data if I need to. Speed is not an issue.

**Comment by Mark-Simulacrum** [comment]
As an update here, I've been contemplating moving to *some* form of database-like solution, in particular as we look to collect increasingly large amounts of data. Today the rustc-timing checkout weighs around 1.6 GB unpacked (and the whole clone is around 5 GB). This is quite small in comparison to today's disk standards, so is not a huge concern - our current solution of snappy-compressed JSON works well in that regard.

As of just today, we've moved to no longer store all of the data on disk in memory. In particular, self profile data is no longer stored but rather deserialized from disk on each request. Given that I would like to begin collecting more data -- e.g. RAM usage, perhaps throughout the compilation, CPU utilization throughout compilation, cache misses, etc. -- I think that this pattern will either need to continue or we will need to explore a database of some kind.

My thought right now is that we may be able to keep the nicety of "just JSON" or at least "easily accessible" data though. In particular, I would like to consider "inverting" the tree somewhat -- today the commits are the root nodes and then we have a series of maps beneath them, but if we invert that such that the leaf nodes are `HashMap<Commit, Statistic>`, roughly speaking, then we keep most of the ease of access for "local editing" but likely gain in ability to easily pull data off of disk on demand rather than predeserializing into memory.

But that idea has not yet been fully fleshed out. I'm going to close this issue for now though because as of today we're no longer using enormous amounts of memory to host the site which removes the primary advantage for using a database (which would keep most data on disk).
