### ISSUE TITLE
can't click latest datapoint in graph

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/rustc-perf#749]
it seems to be slightly out of the graph region and I did not manage to click on it 
![graph](https://user-images.githubusercontent.com/476013/90977356-18374180-e545-11ea-964f-ce77bae01c2a.png)

**Comment by leeoniya** [comment]
> it seems to be slightly out of the graph region and I did not manage to click on it

you don't need to click the exact point; as soon as the series is focused and the tooltip is displayed, a click will take you to the diff. the issue is that the tooltip visibility is not properly toggled on cursor re-entry, even though the series is correctly focused.

https://github.com/leeoniya/uPlot/commit/0331c9b7ae605a5b897ff9d6b2655601b6425d66 are the changes necessary to fix the tooltip issue as well as clipping the `is_interpolated` markers to the plot region, which are currently drawn over the y-axis when zooming in. here's my fixed variant:

https://leeoniya.github.io/uPlot/demos/tooltips-closest.html

the visual issue of the hover-point being cut-off at the edge is unfortunately not easily fixable since the hover-points are in the DOM (and not on canvas) for performance reasons, with `position: absolute`, and their container is `overflow: hidden`, which cuts them off. one work-around is to expand/pad the x and y ranges of the plot to accommodate this, but it's more effort than it's worth, IMO.

**Comment by leeoniya** [comment]
https://github.com/leeoniya/uPlot/commit/da99f21579763b8abb5251c8923be2ef314753ec is a follow-up commit that replaces the clipping code with simply drawing only the interpolated markers which are in view.
