### ISSUE TITLE
I disagree with rustc-perf's assessment of rust-lang/rust#85499

### ISSUE THREAD

**Issue by jyn514** [rust-lang/rustc-perf#887]
rust-lang/rust#85499 is a very large improvement on some cases with moderately large regressions on others. If triagebot isn't sure which, it shouldn't add a label. Right now it seems to give precedence to regressions.

**Comment by jyn514** [comment]
In particular, this led @jackh726 to spend quite a lot of time looking into the regression for not much benefit in the end: https://rust-lang.zulipchat.com/#narrow/stream/247081-t-compiler.2Fperformance/topic/Analyzing.20a.20perf.20regression.

Are there docs somewhere for how to debug regressions? It seems like a lot of manual work and asking around right now.

**Comment by rylev** [comment]
Thanks for reporting this! This issues raises several questions. I'll do my best to list the questions as well as my opinion on what the answers are:

* **Was this issue appropriately labeled?** Regressions accompanied by improvements are still regressions. I think labeling this as a performance regression is the right thing to do. 
* **Should the triage bot be even more conservative with labeling?** Performance regressions require _attention_ (note: I'm not saying they require action) and labeling is the best way to ensure that attention is paid to regressions. Again, I think the labeling here was appropriate.
* **Was the right procedure for @jackh726 to spend time investigating the regression?** Probably not. This is where I see the real breakdown. The intention of the label was not to change any procedure (by encouraging more investigation into performance issues than was already taking place) but to ensure that we can track performance issues so that they're not simply forgotten about. This was a mistake on my part for not better communicating the purpose of the new label. 
* **Are there docs somewhere for how to debug regressions?** Very few (and they are mostly [related to the triage process](https://github.com/rust-lang/rustc-perf/tree/master/triage)). This is something we need to address, but I see it as a separate issue from the labeling.

**Comment by jyn514** [comment]
> This was a mistake on my part for not better communicating the purpose of the new label.

I saw on Zulip you're going to make an announcement in the compiler meeting - that's great, but I think it would be more helpful to put it directly in the comment that rustc-perf posts. Not everyone who works on performance is on the compiler team and they should be made aware too

**Comment by rylev** [comment]
@jyn514 Do you have any suggestions on what the comment should say? Again, I think the label was correct - it _was_ a mixed result. We need to be clear that sometimes mixed results or regressions are ok.

We could for instance only show the following when the the run is categorized as regression or mixed:

"**Note**: performance regressions are sometimes acceptable especially when accompanied by large performance gains or in the case of bug fixes. Make sure to use your best judgement! **If you decide that the performance regression is acceptable remove the label and post your justification for why in a comment**". 

Thoughts?

**Comment by jackh726** [comment]
So, just fyi. I didn't investigate the performance regression because a label. I investigated it because a few benchmarks were showing ~10% regressions. Even beside the 30% *improvement* for deeply-nested-async, I didn't feel really comfortable with that, at least without doing a bit of investigation.

Now that those are down to ~4% (might actually be back to being a bit worse not that the PGO script edit got split out) and my investigation has basically pointed to no easy fix, I'm confident the perf regression for the PR is fine, on balance with the issues it fixes.

In my opinion here, I think a `perf-improvement`, `perf-regression`, or `perf-mixed` label should be applied, if there are significant changes in perf. Regressions or mixed results should probably get a comment if other judgements are applied to the PR. I'm not sure removing the labels are the best option though.

**Comment by Mark-Simulacrum** [comment]
I agree that we shouldn't remove the label -- maybe adding a new label like perf-justified could make sense?

**Comment by rylev** [comment]
Adding a `perf-justified` label and leaving the `perf-regression` seems like a good idea. 

@jackh726 we were considering also having `perf-improvement` and `perf-mixed` but decided that only labeling `perf-regression` might make managing the labels easier. Would you find having perf improvements useful? Do you think distinguishing mixed results and pure regressions is useful?

**Comment by rylev** [comment]
I believe this issue has mostly been addressed:
* we provide more context on posts by the perf bot
* we have a better understanding of noise making labels more accurate

If there are still issues with how we're classifying perf runs, we should open a new, more specific issue.
