### ISSUE TITLE
Try builds have a date of 2000-01-01

### ISSUE THREAD

**Issue by rylev** [rust-lang/rustc-perf#917]
We display dates in the UI, and all try builds have the same date (2000-01-01). Perhaps we should filter that date when returning it from the API.

**Comment by Mark-Simulacrum** [comment]
It's worth noting that I use the date to know what we're comparing against. I think we use 1970s date for artifacts?

So we should expose the artifact type (including try vs master) somewhere I think on the UI, though certainly need not exclusively be through a date.

IIRC the reason for the dates in the first place is that they can be entered instead of commits, so showing them let's you go back and forth to some extent.

**Comment by Kobzol** [comment]
Resolved by https://github.com/rust-lang/rustc-perf/pull/1357, https://github.com/rust-lang/rustc-perf/pull/1393 and https://github.com/rust-lang/rustc-perf/pull/1399, try builds now have the proper date.
